### ISSUE TITLE
different instrument results

### ISSUE THREAD

**Issue by Kflash** [istanbuljs/istanbul-lib-instrument#13]
Coveralls.io and CodeCov both get the same coverage report, but show different result.

Coveralls.io - 66.667%
CodeCov - 71.43%

Could it be issue with comments in the code?

The boilerplate can be found here: https://github.com/Kflash/rachelle

Just click on the Coveralls or the CodeCov badge and see for yourself!

**update**

Code coverage staff wrOTE this regarding the issue:

```js
Looks like the reports expressed line 1 as being covered. I'll review why this is the case and fix it accordingly. The issue is actually in the report and not with codecov processing.

I'll ping you back shortly and have this fixed up. Thank you for your patience ;)

Steve
```

**Comment by bcoe** [comment]
@Kflash sounds like we've narrowed this down to codecov rather than istanbul?

**Comment by Kflash** [comment]
Agree. You can close this.
