### ISSUE TITLE
How do i generate an empty coverage object?

### ISSUE THREAD

**Issue by dmitriiabramov** [istanbuljs/istanbul-lib-instrument#17]
i'm trying to collect coverage for files that don't have tests at all.
The classic way of doing it is just to require a file, but that can become a performance problem and some modules also have side effects.

basically what i think i need is to transpile the file under test into https://github.com/istanbuljs/istanbul-lib-instrument/blob/master/src/visitor.js#L431 this, but without the rest of the file. Is there an easy way to do it right now?

**Comment by dmitriiabramov** [comment]
i guess i can use
```
instrumenter.instrumentSync(source, filename);
instrumenter.fileCoverage;
```

**Comment by bySabi** [comment]
@dmitriiabramov I´m in the process of create a Karma Coverage plugin based on new `istanbul-lib-coverage` and `istanbul-lib-reporter`  new API but I need implement a  nyc  `--all` like solution not covered on current `babel-plugin-istanbul` . 
It seems you are trying to implement a `include all files` too.
Can you give me some advice or code example?

**Comment by dmitriiabramov** [comment]
@bySabi sure! you can look at how it's implemented in Jest
https://github.com/facebook/jest/blob/master/packages/jest-cli/src/reporters/CoverageReporter.js#L62

**Comment by bySabi** [comment]
got it! 
thanks @dmitriiabramov
