### ISSUE TITLE
Faster instrumented code

### ISSUE THREAD

**Issue by mourner** [istanbuljs/istanbul-lib-instrument#21]
Continuation of https://github.com/gotwarlost/istanbul/pull/694 will allow running coverage with almost no overhead, compared to the current situation of instrumented code running 4-5x slower than original, a huge problem in large projects.

The only question I have before I start a PR on this is what option to choose among the following:

1. Change the produced coverage JSON format so that `statements: {'1': 1, '2': 1, '3': 0}` become `statements: [1, 1, 0]`. How much of a breaking change this is and will it also require breaking changes in downstream modules?
2. Change the JSON format during instrumented run but convert it back to the old format in the end. Keeps compatibility but hackish and can lead to ugly code.
3. Try changing the format to use zero indexes (e.g. `statements: {'0': 1, '1': 1, '2': 0}`) — this might be enough to make V8 switch to "fast" mode where it treats it as array rather than dictionary — needs to be checked though.

I'd prefer option 1 but would appreciate hints on the scope of work here. cc @bcoe 

**update**: went with option 3 (zero-based indices).

Thanks!

**Comment by mourner** [comment]
Good news — option 3 seems to bring the same performance benefits while not breaking the API.

**Comment by bcoe** [comment]
@mourner fascinating, would be curious to see the benchmarks on a repo before and after.

Will this mean that we need to translate line #s all over the place though? e.g., in every one of the reports; `'0'` represents the line with coverage correct?

**Comment by mourner** [comment]
Posted some benchmark numbers in the PR (#22).

> Will this mean that we need to translate line #s all over the place though? e.g., in every one of the reports; '0' represents the line with coverage correct?

No, all the keys in `statements`, `branches` and `functions` objects are just unique identifiers so for example `data.s[id]` and `data.statementMap[id]` would refer to the same statement.

**Comment by bcoe** [comment]
@mourner oh, interesting, I had never dug too far into that functionality. How are the identifiers ultimately mapped back to line #s?

**Comment by mourner** [comment]
@bcoe through `*Map` objects — each contains start/end line/column for every statement. The exact number of the identifier is not important as long as you can e.g. iterate over `statementMap` and use the key to access `s[id]` to know how many times the statement was executed.

To sum up, as far as I understand, this should be a non-breaking change.

```js
statementMap: {
    '0': {
        start: {
            line: 3,
            column: 14
        },
        end: {
            line: 3,
            column: 32
        }
    },
```

**Comment by bcoe** [comment]
@gotwarlost would love your thoughts on this; are there any gotchas we're missing?
