### ISSUE TITLE
Arrow Functions Don't Get Location Set Correctly

### ISSUE THREAD

**Issue by epmatsw** [istanbuljs/istanbul-lib-instrument#32]
Given the code:

```javascript
() => A
```

`insertFunctionCounter` in visitor.js passes `path.node.body.loc` as the `loc` to `this.cov.newFunction`. However, `path.node.body.loc` is undefined, so the location ends up looking like:

```
{end: {}, start: {}}
```

which is crashing the HTML report downstream.

**Comment by wyze** [comment]
I'm not able to reproduce this, I always see `path.node.body.loc` being set in all test suites. Could you provide the exact snippet you have that is causing this issue?

**Comment by epmatsw** [comment]
Hmm. What are you seeing for `JSON.stringify(path.node)` in the code above? I'm getting:

```
{
	"type": "FunctionExpression",
	"start": 31,
	"end": 38,
	"loc": {
		"start": {
			"line": 4,
			"column": 0
		},
		"end": {
			"line": 4,
			"column": 7
		}
	},
	"id": null,
	"generator": false,
	"expression": false,
	"async": false,
	"params": [],
	"body": {
		"type": "BlockStatement",
		"body": [{
			"type": "ReturnStatement",
			"argument": {
				"type": "Identifier",
				"start": 37,
				"end": 38,
				"loc": {
					"start": {
						"line": 4,
						"column": 6
					},
					"end": {
						"line": 4,
						"column": 7
					},
					"identifierName": "A"
				},
				"name": "A",
				"leadingComments": null,
				"trailingComments": null
			}
		}],
		"directives": [],
		"_letDone": true
	},
	"leadingComments": null,
	"trailingComments": null,
	"shadow": true
}
```
which does not have a `body.loc`.

**Comment by epmatsw** [comment]
In fact, it seems like just doing:
```
var loc = path.node.body.loc || path.node.loc;
var index = this.cov.newFunction(name, dloc, loc);
```
gives the correct result.

Are there any dependencies I should look for versions of that would alter the AST? I've got `babel-core ^4.16.0` and `babylon ^6.9.1`

**Comment by wyze** [comment]
My `JSON.stringify` when adding this as a test case in this project:

```js
{
  "type": "ArrowFunctionExpression",
  "start": 0,
  "end": 7,
  "loc": {
    "start": {
      "line": 1,
      "column": 0
    },
    "end": {
      "line": 1,
      "column": 7
    }
  },
  "id": null,
  "generator": false,
  "expression": false,
  "async": false,
  "params": [],
  "body": {
    "type": "BlockStatement",
    "body": [
      {
        "type": "ReturnStatement",
        "argument": {
          "type": "Identifier",
          "start": 6,
          "end": 7,
          "loc": {
            "start": {
              "line": 1,
              "column": 6
            },
            "end": {
              "line": 1,
              "column": 7
            },
            "identifierName": "A"
          },
          "name": "A"
        },
        "loc": {
          "start": {
            "line": 1,
            "column": 6
          },
          "end": {
            "line": 1,
            "column": 7
          },
          "identifierName": "A"
        }
      }
    ],
    "directives": [],
    "loc": {
      "start": {
        "line": 1,
        "column": 6
      },
      "end": {
        "line": 1,
        "column": 7
      },
      "identifierName": "A"
    }
  }
}
```

I think you meant `babel-core: ^6.16.0`? If that fallback gives the correct result, I can see that being a reasonable addition, I just wish I could get a failing test case to prove that the change is needed.

**Comment by wyze** [comment]
I am able to produce your exact same AST given this code: 

```js
const B = function() { return A; }
```

But, I still get the location data on `path.node.body.loc`.

**Comment by epmatsw** [comment]
Dang, I wonder if some other plugin is gumming things up. I'll debug some more and update.

**Comment by epmatsw** [comment]
Ugh, sorry about this, PEBKAC. `babel-plugin-istanbul` was getting run in a second stage via `babel.transformFromAst` after the initial babel transform, so it was getting the AST output of `babel.transform`, which doesn't include a `loc` on the `body` of transformed arrow expressions (and probably doesn't produce correct coverage information anyways). Somehow this "worked" with `babel-plugin-__coverage__`, but I don't think it's a really useful scenario to worry about. Moving `babel-plugin-istanbul` to the first stage seems to fix the issue on my end.

**Comment by bcoe** [comment]
@epmatsw awesome, I'm glad you sorted this out 👍
