### ISSUE TITLE
New function name preservation logic regresses binding reassignment

### ISSUE THREAD

**Issue by loganfsmyth** [istanbuljs/istanbul-lib-instrument#34]
The new logic added in https://github.com/istanbuljs/istanbul-lib-instrument/pull/33 introduces issues with function names. Take a case like this:

```
let someFunction = function() {
  someFunction = function(){};
};
```
becomes

```
let someFunction = (coverageStuff, function someFunction() {
  someFunction = function(){};
});
```

which will fail because `someFunction` now references the internal function name binding, rather than the outer one.

This is causing Babel itself to fail to bootstrap because we use this plugin in our tests, and has also been reported by a third-party in https://github.com/babel/babel/issues/5048.

**Comment by bcoe** [comment]
@loganfsmyth I've reverted `latest` to `1.3.0` while we work out some of these edge-cases mind confirming here that things are working again.

**Comment by bcoe** [comment]
@wyze seems like we have a couple edge-cases we're going to need to work out before we can promote `1.3.1` to `latest` also see:

https://github.com/istanbuljs/istanbul-lib-instrument/commit/590abf6730a22e718c6ea211b7048e715664ae66

It feels like we might need to be slightly more clever, with regards to how we maintain the original function name.

**Comment by loganfsmyth** [comment]
Thanks for the quick response, this appear to be working again.

**Comment by bcoe** [comment]
@wyze awesome, once we have these fixes; I will test against babel and a bunch of other repos; there's a spawn-wrap change I'd like to test more thoroughly too.

**Comment by STRML** [comment]
This is also causing issues with destructured assignment:

```js
const [a] = foo.filter((f) => f)
```

becomes:

```
var _ref = (++cov_2ozb893xa5.s[0], foo.filter(function [a](f) {
  ++cov_2ozb893xa5.f[0];
  ++cov_2ozb893xa5.s[1];
  return f;
})),
    a = _ref[0];
```

Notice:

`foo.filter(function [a](f) {`

which is invalid syntax.

**Comment by bcoe** [comment]
should be addressed in: https://github.com/istanbuljs/istanbul-lib-instrument/pull/38
