### ISSUE TITLE
a logo for Istanbul

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/istanbul-lib-instrument#6]
Everyone's favorite test-coverage tool is now an organization \o/ would love help figuring out a logo.

**Comment by isaacs** [comment]
Let me be the first to suggest this terrible idea:

![not-constantinople](https://cloud.githubusercontent.com/assets/9287/16351550/62a0309e-3a1b-11e6-94c2-ed91cf8ea8b6.png)

**Comment by ashleygwilliams** [comment]
a cartoon version of that would probably be p cool actually...

**Comment by isaacs** [comment]
Some other revs on this embarrassing pop culture reference:

![not-constantinople-js](https://cloud.githubusercontent.com/assets/9287/16351824/791f562c-3a1d-11e6-8c2e-5f756e06a247.png)
![not-constantinople-jslogo](https://cloud.githubusercontent.com/assets/9287/16351837/8001e7f2-3a1d-11e6-97a0-5c05696f0801.png)

**Comment by bcoe** [comment]
perhaps something inspired by the They Might Be Giants Logo, keep makes sense once we move `nyc` into this org:

http://laughingsquid.com/wp-content/uploads/tmbg-logo-20101115-094946.jpg

**Comment by isaacs** [comment]
@bcoe Tricky thing about that is TMBG have had a lot of "logos" over the years in varying degrees of officialness and a wide variety of styles.

**Comment by markstory** [comment]
Are you looking for more of an 'istanbul the country' theme, or something more offbeat?

**Comment by bcoe** [comment]
@markstory I was personally thinking maybe a bit more offbeat, focus on the test coverage not city ... maybe like someone covering toast with peanutbutter :p

**Comment by bcoe** [comment]
How about this:

![istanbul](https://cloud.githubusercontent.com/assets/194609/16359093/346babe6-3add-11e6-9274-107919c96a79.png)

**Comment by bcoe** [comment]
@markstory, @chrisdickinson, @isaacs, @ashleygwilliams perhaps as an alternative we go with the JavaScript black and yellow scheme, cut out the red:

![istanbul-black](https://cloud.githubusercontent.com/assets/194609/16359183/7ae6d616-3adf-11e6-82fe-3276e32aab70.png)

**Comment by markstory** [comment]
@bcoe That looks good to me. You'll lose some of the detail at small sizes, but the silhouette is distinct enough. I think that might work better than toast & jam :smile:

**Comment by bcoe** [comment]
@markstory if you got bored and wanted to simplify the silhouette, sure wouldn't turn down your artistic expertise 🎉 

I'm using to use this for the time being. Don't know if you've been playing with ES2015 much? but check this out:

https://github.com/istanbuljs/babel-plugin-istanbul/pull/2

**Comment by gotwarlost** [comment]
@bcoe - nice!

**Comment by gotwarlost** [comment]
@bcoe @gyehuda - I'm reopening this issue since, apparently, we shouldn't be using this logo. The original art is not creative commons? Gil has more details.

**Comment by bcoe** [comment]
@gyehuda @gotwarlost this is a stock photo drawing of the Hagia Sophia landmark, which I purchased off something like IStock Photo and modified quite a bit in photoshop myself to make it into a logo. Is there a specific complaint?

**Comment by bcoe** [comment]
@gyehuda @gotwarlost I'll happily photoshop an alternative drawing, stock photo, linocut, etc., of the landmark into a similar logo if you can find one that passes your legal review.

**Comment by jameswomack** [comment]
Are you leaning toward the landmark still or want to go back to considering concepts that refer to test coverage or the results of test coverage?

**Comment by gyehuda** [comment]
@bcoe aha, I was not aware that you purchased this with the right to make a derivative work. I was informed by someone that the image looks like one subject to copyright and thus it appeared that it was simply copied. So I asked if we were confident that it was OK that we use this image. If indeed we have rights to it, great. However, it may be best that the resultant logo look sufficiently distinct so that if someone else points this out again, it would be even more apparent that this is a distinct logo that is rightfully being used by this project. Thanks for giving attention to this -- and thanks also for purchasing the rights in the first place.

**Comment by bcoe** [comment]
@jameswomack @gyehuda @gotwarlost definitely open to artistic interpretation! I liked the idea of pulling in a landmark from Istanbul because it fits well with the name -- but we don't have to keep in that direction.

Keeping an interchangeable color scheme would be nice because we have this site we'll need to update:

https://istanbul.js.org/

**Comment by gabra** [comment]
I didn't see any wordmarks yet so here are some ideas. I was thinking about what the culture itself feels like. Medici script seemed to have an east-meets-west feeling to it, and is by Hermann Zapf. The fleurons and jewels are more neoclassical, but the overlapping of them starts to give the logo a complex look..feedback or thoughts?

<img width="1753" alt="screenshot 2016-10-20 13 36 57" src="https://cloud.githubusercontent.com/assets/757928/19577336/cb162554-96cb-11e6-9366-30c076e12546.png">

**Comment by gabra** [comment]
Some more logos, using an actual byzantine typeface this time: 
![image](https://cloud.githubusercontent.com/assets/757928/19611298/e6621ad2-9795-11e6-93e5-b041c8264b70.png)

**Comment by bcoe** [comment]
I was looking for the original purchase so I could confirm the license.
Part of me would like to redraw a similar image just to eliminate any
potential concerns.

I'll try to find the license I bought in the mean time.
